// Oberon-07 runtime library (C++20)
//
// Implements the standard Oberon modules:
//   Out  — text output (Out.String, Out.Ln, Out.Int, Out.Real, Out.Char)
//   In   — text input  (In.Int,  In.Real,  In.Char)
//
// Also implements:
//   Oberon_NEW(size) — heap allocation for NEW(ptr)
//
// All symbols use extern "C" to match the unmangled names emitted by the
// LLVM code generator.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

extern "C" {

// ---------------------------------------------------------------------------
// Out module
// ---------------------------------------------------------------------------

// Out.String(s)  — write a NUL-terminated string
void Out_String(const char* s) {
    if (s) std::fputs(s, stdout);
}

// Out.Ln  — write a newline and flush
void Out_Ln() {
    std::putchar('\n');
    std::fflush(stdout);
}

// Out.Int(n, w)  — write integer n right-justified in a field of width w
//   If w <= 0 the number is printed with a leading space (Oberon convention).
void Out_Int(int64_t n, int64_t w) {
    // Build the decimal representation then pad.
    char buf[32];
    int len = std::snprintf(buf, sizeof(buf), "%lld", static_cast<long long>(n));
    // Pad with spaces on the left if the field is wider than the number.
    for (int64_t i = len; i < w; ++i) std::putchar(' ');
    std::fputs(buf, stdout);
}

// Out.Real(x, w) — write real x right-justified in a field of width w
//   Uses Oberon-style scientific notation with 7 significant digits.
void Out_Real(double x, int64_t w) {
    char buf[64];
    int len = std::snprintf(buf, sizeof(buf), "% .7G", x);
    for (int64_t i = len; i < w; ++i) std::putchar(' ');
    std::fputs(buf, stdout);
}

// Out.Char(c)  — write a single character
void Out_Char(char c) {
    std::putchar(static_cast<unsigned char>(c));
}

// ---------------------------------------------------------------------------
// In module
// ---------------------------------------------------------------------------

// In.Int(VAR n)  — read a decimal integer from stdin
void In_Int(int64_t* n) {
    long long tmp = 0;
    if (std::scanf("%lld", &tmp) == 1)
        *n = static_cast<int64_t>(tmp);
}

// In.Real(VAR x)  — read a floating-point number from stdin
void In_Real(double* x) {
    std::scanf("%lf", x);
}

// In.Char(VAR c)  — read a single character from stdin (skips newlines)
void In_Char(char* c) {
    int ch;
    // skip whitespace/newlines
    do { ch = std::getchar(); } while (ch == '\n' || ch == '\r' || ch == ' ');
    if (ch != EOF) *c = static_cast<char>(ch);
}

// ---------------------------------------------------------------------------
// Heap allocation (used by NEW built-in)
// ---------------------------------------------------------------------------

// Oberon_Trap() — called by ASSERT on failure; terminates the program.
[[noreturn]] void Oberon_Trap() {
    std::fputs("Oberon runtime: assertion failed\n", stderr);
    std::abort();
}

// Oberon_NEW(size) — allocate `size` zero-initialised bytes; abort on OOM.
void* Oberon_NEW(int64_t size) {
    if (size <= 0) size = 1;
    void* p = std::calloc(1, static_cast<std::size_t>(size));
    if (!p) {
        std::fputs("Oberon runtime: out of memory\n", stderr);
        std::abort();
    }
    return p;
}

// Forward declaration of the Oberon module entry point (generated by oberonc).
void oberon_main();

} // extern "C"

int main() {
    oberon_main();
    return 0;
}
